<?php

namespace MDV\PriorityBundle\Repository;
use Doctrine\Common\Collections\Criteria;
use MDV\PriorityBundle\Entity\Issue;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Delete all issues with other keys than given
     *
     * @param array $keys
     * @return int nr. affected
     */
    public function deleteOtherKeys($keys)
    {
        $alias = __CLASS__;
        $qb = $this->createQueryBuilder($alias);
        $qb->delete()->where($qb->expr()->notIn("{$alias}.jiraKey", $keys));
        return $qb->getQuery()->execute();
    }

    /**
     * @param Issue $issue
     */
    public function persist(Issue $issue)
    {
        $this->getEntityManager()->persist($issue);
    }

    /**
     *
     */
    public function flush()
    {
        $this->getEntityManager()->flush();
    }

}
