<?php

namespace MDV\PriorityBundle\Repository;
use MDV\PriorityBundle\Entity\Priority;

/**
 * PriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriorityRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Priority $priority
     */
    public function persist(Priority $priority)
    {
        $this->getEntityManager()->persist($priority);
    }

    /**
     * @param Priority|null $priority
     */
    public function flush(Priority $priority = null)
    {
        if (null !== $priority) {
            $this->persist($priority);
        }

        $this->getEntityManager()->flush();
    }
}
