<?php

namespace MDV\PriorityBundle\Repository;
use MDV\PriorityBundle\Entity\Stakeholder;

/**
 * StakeholderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StakeholderRepository extends \Doctrine\ORM\EntityRepository
{
    public function persist(Stakeholder $stakeholder) {
        $this->getEntityManager()->persist($stakeholder);
    }

    public function flush()
    {
        $this->getEntityManager()->flush();
    }
}
