<?php

namespace MDV\PriorityBundle\Repository;
use Doctrine\ORM\Query;
use MDV\PriorityBundle\Entity\Vote;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retrieve nr. votes
     *
     * @return int
     */
    public function getTotalVotes()
    {
        $alias = __CLASS__;
        $qb = $this->createQueryBuilder($alias);
        $qb->select("SUM({$alias}.vote)");
        return (int)$qb->getQuery()->execute(null, Query::HYDRATE_SINGLE_SCALAR);
    }

    /**
     * @param Vote $vote
     */
    public function persist(Vote $vote)
    {
        $this->getEntityManager()->persist($vote);
    }

    /**
     * @return void
     */
    public function flush(Vote $vote = null)
    {
        if (null !== $vote) {
            $this->persist($vote);
        }

        $this->getEntityManager()->flush();
    }
}
