mdv_priority_homepage:
    path:     /
    defaults: { _controller: MDVPriorityBundle:Vote:index }

mdv_priority_settings:
    path:     /settings
    defaults: { _controller: MDVPriorityBundle:Vote:settings }
