MDV\PriorityBundle\Entity\Settings:
    type: entity
    table: null
    repositoryClass: MDV\PriorityBundle\Repository\SettingsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        open:
            type: boolean
    lifecycleCallbacks: {  }
